// Code generated by gen-cdp-tools; DO NOT EDIT.

package generated

import "github.com/dsbissett/office-addin-mcp/internal/tools"

// RegisterGenerated adds every code-generated CDP tool to the registry.
func RegisterGenerated(r *tools.Registry) {
	RegisterTest(r)
}
