// Code generated by gen-cdp-tools; DO NOT EDIT.

package generated

import "github.com/dsbissett/office-addin-mcp/internal/tools"

// Domains lists every code-generated CDP domain in alphabetical order. Used
// by callers that need to validate a user-supplied --cdp-domains list.
var Domains = []string{
	"Test",
}

// RegisterGenerated adds every code-generated CDP tool to the registry.
func RegisterGenerated(r *tools.Registry) {
	RegisterTest(r)
}

// RegisterGeneratedFiltered registers only the domains whose name appears in
// allowed. Empty map registers nothing; pass nil/empty plus call
// RegisterGenerated separately for the unfiltered behavior.
func RegisterGeneratedFiltered(r *tools.Registry, allowed map[string]bool) {
	if allowed["Test"] {
		RegisterTest(r)
	}
}
