// Code generated by gen-cdp-tools; DO NOT EDIT.
// Source: cdp/manifest.yaml + cdp/protocol/{browser,js}_protocol.json (see cdp/protocol/VERSION).

package generated

import (
	"context"
	"encoding/json"

	"github.com/dsbissett/office-addin-mcp/internal/tools"
)

// --- Test.draw ---

const testDrawSchema = "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"title\":\"cdp.test.draw parameters\",\"type\":\"object\",\"properties\":{\"color\":{\"enum\":[\"red\",\"green\",\"blue\"],\"type\":\"string\"},\"label\":{\"type\":\"string\"},\"targetId\":{\"type\":\"string\",\"description\":\"Exact target id; mutually exclusive with urlPattern.\"},\"urlPattern\":{\"type\":\"string\",\"description\":\"Substring of the target URL; mutually exclusive with targetId.\"},\"width\":{\"type\":\"integer\"}},\"required\":[\"color\"],\"additionalProperties\":false}"

type testDrawParams struct {
	Color      string `json:"color"`
	Width      int64  `json:"width,omitempty"`
	Label      string `json:"label,omitempty"`
	TargetID   string `json:"targetId,omitempty"`
	URLPattern string `json:"urlPattern,omitempty"`
}

func NewTestDraw() tools.Tool {
	return tools.Tool{
		Name:        "cdp.test.draw",
		Description: "Draws a `pixel` on the canvas (the backtick is intentional — it stresses the schema-literal escaping). (CDP: Test.draw)",
		Schema:      json.RawMessage(testDrawSchema),
		Run:         runTestDraw,
	}
}

func runTestDraw(ctx context.Context, raw json.RawMessage, env *tools.RunEnv) tools.Result {
	var p testDrawParams
	if len(raw) > 0 {
		if err := json.Unmarshal(raw, &p); err != nil {
			return tools.Fail(tools.CategoryValidation, "param_decode", err.Error(), false)
		}
	}
	att, err := env.Attach(ctx, tools.TargetSelector{TargetID: p.TargetID, URLPattern: p.URLPattern})
	if err != nil {
		return tools.Fail(tools.CategoryNotFound, "attach_failed", err.Error(), false)
	}
	if err := env.EnsureEnabled(ctx, att.SessionID, "Test"); err != nil {
		return tools.ClassifyCDPErr("enable_failed", err)
	}
	cdpParams := struct {
		Color string `json:"color"`
		Width int64  `json:"width,omitempty"`
		Label string `json:"label,omitempty"`
	}{
		Color: p.Color,
		Width: p.Width,
		Label: p.Label,
	}
	out, err := att.Conn.Send(ctx, att.SessionID, "Test.draw", cdpParams)
	if err != nil {
		return tools.ClassifyCDPErr("test_draw_failed", err)
	}
	return tools.OK(json.RawMessage(out))
}

// --- Test.ping ---

const testPingSchema = "{\"$schema\":\"https://json-schema.org/draft/2020-12/schema\",\"title\":\"cdp.test.ping parameters\",\"type\":\"object\",\"properties\":{\"targetId\":{\"type\":\"string\",\"description\":\"Exact target id; mutually exclusive with urlPattern.\"},\"urlPattern\":{\"type\":\"string\",\"description\":\"Substring of the target URL; mutually exclusive with targetId.\"}},\"additionalProperties\":false}"

type testPingParams struct {
	TargetID   string `json:"targetId,omitempty"`
	URLPattern string `json:"urlPattern,omitempty"`
}

func NewTestPing() tools.Tool {
	return tools.Tool{
		Name:        "cdp.test.ping",
		Description: "Health check. (CDP: Test.ping)",
		Schema:      json.RawMessage(testPingSchema),
		Run:         runTestPing,
	}
}

func runTestPing(ctx context.Context, raw json.RawMessage, env *tools.RunEnv) tools.Result {
	var p testPingParams
	if len(raw) > 0 {
		if err := json.Unmarshal(raw, &p); err != nil {
			return tools.Fail(tools.CategoryValidation, "param_decode", err.Error(), false)
		}
	}
	att, err := env.Attach(ctx, tools.TargetSelector{TargetID: p.TargetID, URLPattern: p.URLPattern})
	if err != nil {
		return tools.Fail(tools.CategoryNotFound, "attach_failed", err.Error(), false)
	}
	if err := env.EnsureEnabled(ctx, att.SessionID, "Test"); err != nil {
		return tools.ClassifyCDPErr("enable_failed", err)
	}
	out, err := att.Conn.Send(ctx, att.SessionID, "Test.ping", nil)
	if err != nil {
		return tools.ClassifyCDPErr("test_ping_failed", err)
	}
	return tools.OK(json.RawMessage(out))
}

// RegisterTest adds every generated Test tool to the registry.
func RegisterTest(r *tools.Registry) {
	r.MustRegister(NewTestDraw())
	r.MustRegister(NewTestPing())
}
