// Command gen-cdp-tools generates Go MCP tool wrappers for every CDP method
// declared in cdp/manifest.yaml.
//
// Inputs:
//   - cdp/manifest.yaml                  (policy: which methods, scope, autoEnable, dangerous, binaryField)
//   - cdp/protocol/browser_protocol.json (parameter & type definitions)
//   - cdp/protocol/js_protocol.json      (parameter & type definitions)
//
// Output: one Go file per domain in -out, plus register_generated.go that
// fans out to each domain's RegisterX. All files carry the cdpgen_smoke
// build tag until P4 — the dispatcher does not see them.
//
// Determinism: all map iterations sort keys; gofmt is run in-process. Two
// successive runs against the same inputs produce byte-identical output —
// CI enforces this with `go generate ./... && git diff --exit-code`.
package main

import (
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

func main() {
	manifestPath := flag.String("manifest", "cdp/manifest.yaml", "path to manifest YAML")
	browserProtoPath := flag.String("browser", "cdp/protocol/browser_protocol.json", "path to browser_protocol.json")
	jsProtoPath := flag.String("js", "cdp/protocol/js_protocol.json", "path to js_protocol.json")
	outDir := flag.String("out", "internal/tools/cdptool/generated", "output directory")
	docsPath := flag.String("docs", "docs/cdp-tools.md", "tool index markdown output (empty disables)")
	flag.Parse()

	if err := run(*manifestPath, *browserProtoPath, *jsProtoPath, *outDir); err != nil {
		fmt.Fprintln(os.Stderr, "gen-cdp-tools:", err)
		os.Exit(1)
	}
	if *docsPath != "" {
		if err := writeDocs(*manifestPath, *browserProtoPath, *jsProtoPath, *docsPath); err != nil {
			fmt.Fprintln(os.Stderr, "gen-cdp-tools docs:", err)
			os.Exit(1)
		}
	}
}

// writeDocs emits a domain-organized tool index for human reading. Lives
// alongside the Go output so reviewers and integrators can cross-reference
// the generated tool surface without reading every <domain>.go.
func writeDocs(manifestPath, browserPath, jsPath, dest string) error {
	manifest, err := LoadManifest(manifestPath)
	if err != nil {
		return err
	}
	browser, err := LoadProtocol(browserPath)
	if err != nil {
		return err
	}
	js, err := LoadProtocol(jsPath)
	if err != nil {
		return err
	}
	proto := MergeProtocols(browser, js)
	domainIdx, _ := proto.Index()

	var b strings.Builder
	fmt.Fprintf(&b, "<!-- Code generated by gen-cdp-tools; DO NOT EDIT. -->\n")
	fmt.Fprintf(&b, "# Code-generated CDP tools\n\n")
	fmt.Fprintf(&b, "Source: [`cdp/manifest.yaml`](../cdp/manifest.yaml) + vendored protocol JSON in [`cdp/protocol/`](../cdp/protocol/).\n")
	fmt.Fprintf(&b, "Run `go generate ./...` to refresh after edits to either.\n\n")
	fmt.Fprintf(&b, "Conventions:\n")
	fmt.Fprintf(&b, "- Every tool name has the shape `cdp.<lowerDomain>.<lowerMethod>`.\n")
	fmt.Fprintf(&b, "- Target-scoped tools accept optional `targetId` / `urlPattern` selectors.\n")
	fmt.Fprintf(&b, "- Tools marked **dangerous** refuse unless the dispatcher was started with `--allow-dangerous-cdp` (or `OAMCP_ALLOW_DANGEROUS_CDP=1`).\n")
	fmt.Fprintf(&b, "- Tools marked **binary** accept an optional `outputPath`; setting it redirects the base64 payload to disk and returns `{path,sizeBytes,mimeType}`.\n\n")

	domains := make([]string, 0, len(manifest.Domains))
	for d := range manifest.Domains {
		domains = append(domains, d)
	}
	sort.Strings(domains)
	for _, d := range domains {
		dom := manifest.Domains[d]
		scope := dom.Scope
		if scope == "" {
			scope = manifest.Defaults.Scope
		}
		flags := []string{"scope: " + scope}
		if dom.AutoEnable {
			flags = append(flags, "autoEnable")
		}
		fmt.Fprintf(&b, "## %s — %s\n\n", d, strings.Join(flags, ", "))

		methods := make([]string, 0, len(dom.Methods))
		for m := range dom.Methods {
			methods = append(methods, m)
		}
		sort.Strings(methods)
		for _, m := range methods {
			mc := dom.Methods[m]
			tags := []string{}
			if mc.Dangerous {
				tags = append(tags, "**dangerous**")
			}
			if mc.BinaryField != "" {
				tags = append(tags, fmt.Sprintf("**binary** (`%s` → `%s`)", mc.BinaryField, mc.BinaryMimeType))
			}
			suffix := ""
			if len(tags) > 0 {
				suffix = " — " + strings.Join(tags, ", ")
			}
			desc := ""
			if pdom := domainIdx[d]; pdom != nil {
				if cmd := pdom.FindCommand(m); cmd != nil {
					desc = strings.TrimSpace(cmd.Description)
				}
			}
			if desc != "" {
				desc = " " + collapseWhitespace(desc)
			}
			fmt.Fprintf(&b, "- `cdp.%s.%s`%s%s\n", lowerFirst(d), m, suffix, desc)
		}
		fmt.Fprintln(&b)
	}

	if err := os.MkdirAll(filepath.Dir(dest), 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", filepath.Dir(dest), err)
	}
	return writeIfChanged(dest, []byte(b.String()))
}

func collapseWhitespace(s string) string {
	var out strings.Builder
	prevSpace := false
	for _, r := range s {
		if r == '\n' || r == '\r' || r == '\t' {
			r = ' '
		}
		if r == ' ' {
			if prevSpace {
				continue
			}
			prevSpace = true
		} else {
			prevSpace = false
		}
		out.WriteRune(r)
	}
	return strings.TrimSpace(out.String())
}

func run(manifestPath, browserPath, jsPath, outDir string) error {
	manifest, err := LoadManifest(manifestPath)
	if err != nil {
		return err
	}
	browser, err := LoadProtocol(browserPath)
	if err != nil {
		return err
	}
	js, err := LoadProtocol(jsPath)
	if err != nil {
		return err
	}
	proto := MergeProtocols(browser, js)
	domainIdx, typeIdx := proto.Index()
	resolver := &Resolver{Types: typeIdx}

	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", outDir, err)
	}

	// Walk the manifest's domains in sorted order so output ordering stays
	// stable regardless of YAML map iteration order.
	domainNames := make([]string, 0, len(manifest.Domains))
	for d := range manifest.Domains {
		domainNames = append(domainNames, d)
	}
	sort.Strings(domainNames)

	emitted := make([]string, 0, len(domainNames))
	for _, domName := range domainNames {
		domCfg := manifest.Domains[domName]
		protoDom, ok := domainIdx[domName]
		if !ok {
			return fmt.Errorf("manifest domain %q not in protocol files", domName)
		}
		gen, err := buildDomainGen(manifest, resolver, protoDom, domName, domCfg)
		if err != nil {
			return fmt.Errorf("domain %s: %w", domName, err)
		}
		if len(gen.Methods) == 0 {
			continue
		}
		body, err := RenderDomain(gen)
		if err != nil {
			return fmt.Errorf("render %s: %w", domName, err)
		}
		path := filepath.Join(outDir, strings.ToLower(domName)+".go")
		if err := writeIfChanged(path, body); err != nil {
			return err
		}
		emitted = append(emitted, domName)
	}

	regBody, err := RenderRegister(emitted)
	if err != nil {
		return fmt.Errorf("render register: %w", err)
	}
	if err := writeIfChanged(filepath.Join(outDir, "register_generated.go"), regBody); err != nil {
		return err
	}
	if err := writeIfChanged(filepath.Join(outDir, "doc.go"), RenderDoc()); err != nil {
		return err
	}
	return nil
}

// buildDomainGen turns a manifest domain entry + protocol domain into a
// DomainGen ready for the template.
func buildDomainGen(m *Manifest, r *Resolver, protoDom *Domain, domName string, domCfg ManifestDomain) (DomainGen, error) {
	scope := domCfg.Scope
	if scope == "" {
		scope = m.Defaults.Scope
	}

	// Sorted method iteration for deterministic output.
	methodNames := make([]string, 0, len(domCfg.Methods))
	for n := range domCfg.Methods {
		methodNames = append(methodNames, n)
	}
	sort.Strings(methodNames)

	out := DomainGen{Domain: domName}
	for _, mname := range methodNames {
		mcfg := domCfg.Methods[mname]
		cmd := protoDom.FindCommand(mname)
		if cmd == nil {
			return out, fmt.Errorf("method %s.%s not in protocol", domName, mname)
		}
		mg, err := buildMethodGen(m, r, domName, scope, domCfg.AutoEnable, *cmd, mcfg)
		if err != nil {
			return out, fmt.Errorf("method %s.%s: %w", domName, mname, err)
		}
		out.Methods = append(out.Methods, mg)
	}
	return out, nil
}

func buildMethodGen(m *Manifest, r *Resolver, domain, scope string, autoEnable bool, cmd Command, mcfg ManifestMethod) (MethodGen, error) {
	toolName := fmt.Sprintf("%s.%s.%s", m.Defaults.ToolPrefix, lowerFirst(domain), cmd.Name)
	prefix := lowerFirst(domain) + capitalize(cmd.Name)

	desc := strings.TrimSpace(cmd.Description)
	if mcfg.DescriptionOverride != "" {
		desc = mcfg.DescriptionOverride
	}
	if desc == "" {
		desc = fmt.Sprintf("CDP %s.%s.", domain, cmd.Name)
	}
	desc += fmt.Sprintf(" (CDP: %s.%s)", domain, cmd.Name)

	includeSelectors := scope == "target"
	includeOutputPath := mcfg.BinaryField != ""
	schema, fields, err := FieldsToSchema(r, domain, toolName+" parameters", cmd.Parameters, includeSelectors, includeOutputPath)
	if err != nil {
		return MethodGen{}, fmt.Errorf("schema: %w", err)
	}

	// CDP-only fields (non-selector, non-outputPath) used for the projected
	// struct sent over the wire. For browser-scoped non-binary tools every
	// param is a CDP field.
	cdpFields := make([]FieldSchema, 0, len(fields))
	for _, f := range fields {
		switch f.Name {
		case "targetId", "urlPattern", "outputPath":
			continue
		}
		cdpFields = append(cdpFields, f)
	}

	return MethodGen{
		Domain:         domain,
		Method:         cmd.Name,
		ToolName:       toolName,
		Title:          toolName + " parameters",
		Description:    desc,
		Scope:          scope,
		AutoEnable:     autoEnable,
		Dangerous:      mcfg.Dangerous,
		BinaryField:    mcfg.BinaryField,
		BinaryMimeType: mcfg.BinaryMimeType,
		SchemaConst:    prefix + "Schema",
		StructType:     prefix + "Params",
		NewFunc:        "New" + capitalize(domain) + capitalize(cmd.Name),
		RunFunc:        "run" + capitalize(domain) + capitalize(cmd.Name),
		FailureCode:    methodFailureCode(domain, cmd.Name),
		SchemaLiteral:  strconv.Quote(string(schema)),
		Fields:         fields,
		CDPFields:      cdpFields,
		HasCDPParams:   len(cdpFields) > 0,
		HasUserParams:  len(fields) > 0,
	}, nil
}

// writeIfChanged writes content to path only if the existing bytes differ.
// This keeps mtimes stable when generation is idempotent — important for
// CI's `go generate && git diff --exit-code` check on Windows where mtime
// granularity can confuse build caches.
func writeIfChanged(path string, content []byte) error {
	existing, err := os.ReadFile(path)
	if err == nil && bytesEqual(existing, content) {
		return nil
	}
	if err := os.WriteFile(path, content, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	return nil
}

func bytesEqual(a, b []byte) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	return strings.ToLower(s[:1]) + s[1:]
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	return strings.ToUpper(s[:1]) + s[1:]
}
