package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
	"text/template"
)

// MethodGen holds everything the template needs to render one method.
type MethodGen struct {
	Domain         string // "Page"
	Method         string // "navigate"
	ToolName       string // "cdp.page.navigate"
	Title          string // "cdp.page.navigate parameters" (used in JSON Schema title)
	Description    string
	Scope          string // "browser" or "target"
	AutoEnable     bool
	Dangerous      bool   // emit env.AllowDangerous guard at top of Run
	BinaryField    string // result field decoded to outputPath when caller supplies it
	BinaryMimeType string // mime type returned alongside outputPath
	SchemaConst    string // identifier for the schema constant
	StructType     string // identifier for the params struct
	NewFunc        string // identifier for the factory func
	RunFunc        string // identifier for the run func
	FailureCode    string // e.g. "page_navigate_failed"
	SchemaLiteral  string // pre-quoted Go string literal for the schema JSON (CDP descriptions contain backticks, so raw strings won't work)
	Fields         []FieldSchema
	CDPFields      []FieldSchema // Fields with selector + outputPath entries removed (CDP projection)
	HasCDPParams   bool          // true if CDP message includes any fields
	HasUserParams  bool          // true if Fields (incl. selectors / outputPath) is non-empty
}

// DomainGen aggregates methods for one domain into one generated Go file.
type DomainGen struct {
	Domain  string // "Page"
	Methods []MethodGen
}

const fileTemplate = `// Code generated by gen-cdp-tools; DO NOT EDIT.
// Source: cdp/manifest.yaml + cdp/protocol/{browser,js}_protocol.json (see cdp/protocol/VERSION).

package generated

import (
	"context"
	"encoding/json"

	"github.com/dsbissett/office-addin-mcp/internal/tools"
)

{{ range .Methods }}
// --- {{ .Domain }}.{{ .Method }} ---

const {{ .SchemaConst }} = {{ .SchemaLiteral }}

type {{ .StructType }} struct {
{{- range .Fields }}
	{{ .GoName }} {{ .GoType }} ` + "`{{ .JSONTag }}`" + `
{{- end }}
}

func {{ .NewFunc }}() tools.Tool {
	return tools.Tool{
		Name:        "{{ .ToolName }}",
		Description: {{ printf "%q" .Description }},
		Schema:      json.RawMessage({{ .SchemaConst }}),
		Run:         {{ .RunFunc }},
	}
}

func {{ .RunFunc }}(ctx context.Context, raw json.RawMessage, env *tools.RunEnv) tools.Result {
{{- if .Dangerous }}
	if !env.AllowDangerous {
		return tools.Fail(tools.CategoryUnsupported, "dangerous_disabled",
			"{{ .Domain }}.{{ .Method }} is gated behind --allow-dangerous-cdp / OAMCP_ALLOW_DANGEROUS_CDP=1", false)
	}
{{- end }}
{{- if .HasUserParams }}
	var p {{ .StructType }}
	if len(raw) > 0 {
		if err := json.Unmarshal(raw, &p); err != nil {
			return tools.Fail(tools.CategoryValidation, "param_decode", err.Error(), false)
		}
	}
{{- end }}
{{- if eq .Scope "target" }}
	att, err := env.Attach(ctx, tools.TargetSelector{TargetID: p.TargetID, URLPattern: p.URLPattern})
	if err != nil {
		return tools.Fail(tools.CategoryNotFound, "attach_failed", err.Error(), false)
	}
{{- if .AutoEnable }}
	if err := env.EnsureEnabled(ctx, att.SessionID, "{{ .Domain }}"); err != nil {
		return tools.ClassifyCDPErr("enable_failed", err)
	}
{{- end }}
{{- if .HasCDPParams }}
	cdpParams := struct {
{{- range .CDPFields }}
		{{ .GoName }} {{ .GoType }} ` + "`{{ .JSONTag }}`" + `
{{- end }}
	}{
{{- range .CDPFields }}
		{{ .GoName }}: p.{{ .GoName }},
{{- end }}
	}
	out, err := att.Conn.Send(ctx, att.SessionID, "{{ .Domain }}.{{ .Method }}", cdpParams)
{{- else }}
	out, err := att.Conn.Send(ctx, att.SessionID, "{{ .Domain }}.{{ .Method }}", nil)
{{- end }}
{{- else }}
	conn, err := env.Conn(ctx)
	if err != nil {
		return tools.Fail(tools.CategoryConnection, "conn_failed", err.Error(), false)
	}
{{- if .HasCDPParams }}
	out, err := conn.Send(ctx, "", "{{ .Domain }}.{{ .Method }}", p)
{{- else }}
	out, err := conn.Send(ctx, "", "{{ .Domain }}.{{ .Method }}", nil)
{{- end }}
{{- end }}
	if err != nil {
		return tools.ClassifyCDPErr("{{ .FailureCode }}", err)
	}
{{- if .BinaryField }}
	if p.OutputPath != "" {
		return tools.WriteBinaryFieldOutput(json.RawMessage(out), "{{ .BinaryField }}", "{{ .BinaryMimeType }}", p.OutputPath)
	}
{{- end }}
	return tools.OK(json.RawMessage(out))
}
{{ end }}
// Register{{ .Domain }} adds every generated {{ .Domain }} tool to the registry.
func Register{{ .Domain }}(r *tools.Registry) {
{{- range .Methods }}
	r.MustRegister({{ .NewFunc }}())
{{- end }}
}
`

// RenderDomain produces the Go source for a single domain file. Returns
// gofmt-formatted bytes.
func RenderDomain(d DomainGen) ([]byte, error) {
	tmpl, err := template.New("domain").Parse(fileTemplate)
	if err != nil {
		return nil, fmt.Errorf("parse template: %w", err)
	}
	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, d); err != nil {
		return nil, fmt.Errorf("execute template: %w", err)
	}
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		return nil, fmt.Errorf("gofmt: %w\n--- raw ---\n%s", err, buf.String())
	}
	return formatted, nil
}

// RenderRegister builds register_generated.go which fans out to each
// domain's RegisterX. Domain order is sorted for determinism.
func RenderRegister(domains []string) ([]byte, error) {
	sorted := append([]string(nil), domains...)
	sort.Strings(sorted)
	var buf bytes.Buffer
	buf.WriteString(`// Code generated by gen-cdp-tools; DO NOT EDIT.

package generated

import "github.com/dsbissett/office-addin-mcp/internal/tools"

// RegisterGenerated adds every code-generated CDP tool to the registry.
func RegisterGenerated(r *tools.Registry) {
`)
	for _, d := range sorted {
		fmt.Fprintf(&buf, "\tRegister%s(r)\n", d)
	}
	buf.WriteString("}\n")
	return format.Source(buf.Bytes())
}

// RenderDoc emits the package-level doc.go containing the //go:generate
// directive. Lives outside the build tag so editors and `go generate ./...`
// see it unconditionally.
func RenderDoc() []byte {
	const body = `// Package generated contains code-generated CDP tool wrappers.
// Do not edit any file in this directory by hand — run go generate from
// the repo root (or invoke gen-cdp-tools directly) to refresh.

//go:generate go run ../../../../cmd/gen-cdp-tools -manifest ../../../../cdp/manifest.yaml -browser ../../../../cdp/protocol/browser_protocol.json -js ../../../../cdp/protocol/js_protocol.json -out .

package generated
`
	return []byte(body)
}

// methodFailureCode renders snake_case "domain_method_failed" for use as the
// envelope failure code. e.g. "Page", "navigate" -> "page_navigate_failed".
func methodFailureCode(domain, method string) string {
	return strings.ToLower(domain) + "_" + lowerCamelToSnake(method) + "_failed"
}

func lowerCamelToSnake(s string) string {
	var out strings.Builder
	for i, r := range s {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				out.WriteByte('_')
			}
			out.WriteRune(r + ('a' - 'A'))
			continue
		}
		out.WriteRune(r)
	}
	return out.String()
}
